### PR TITLE
fix/68-create-private-key-with-right-permissions

### PR DESCRIPTION
**Pull request by RadigarHub**
- Create private.key file with 644 permissions when execute make generate-private-key

### CODE REVIEW

**Comment by moein** [comment]
@RadigarHub Can you please add the command to generate the public key as well?
`openssl rsa -in private.key -pubout -out public.key`

**Comment by RadigarHub** [comment]
Of course

**Comment by moein** [comment]
@RadigarHub Sorry one last change
Let's make it one make function (so you generate the private key, give it the right permission and generate public key)
Also after generation move both the private key and public key to var/oauth (create the directory if it doesn't exist)

**Comment by RadigarHub** [comment]
Ok, no problem

**Comment by RadigarHub** [comment]
I got confused with the folder location. I will correct it.

**Comment by juanwilde** [comment]
Thanks @RadigarHub <3

**Pull request merged**
